# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=5)),
                ('stu_sex', models.BooleanField()),
                ('stu_tel', models.CharField(max_length=11)),
                ('c_id', models.IntegerField(max_length=3)),
                ('stu_create_time', models.DateTimeField(auto_now_add=True)),
                ('stu_change_time', models.DateTimeField(auto_now=True)),
                ('is_existed', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'tbstudent',
            },
        ),
    ]
